http:
  host: localhost
  port: 3000

database:
  host: localhost
  port: 27017
  name: Nestjs-boilerplate

docs:
  enable: true
  title: Nestjs-boilerplate
  description: The Nestjs-boilerplate API description
  path: api/docs
  versions:
    - version: 1.0
      tags:
      